version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "DSharpPlus*"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
      entity-framework:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Npgsql.EntityFrameworkCore*"
      test-framework:
        patterns:
          - "Microsoft.NET.Test*"
          - "MSTest*"
          - "NSubstitute*"
          - "FluentAssertions*"
      microsoft:
        patterns:
          - "Microsoft.*"
      image-sharp:
        patterns:
          - "SixLabors.ImageSharp*"
