version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "[skip ci] "
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
        dsharp-packages:
            patterns:
            - "DSharpPlus*"
        other-packages:
            patterns:
            - "*"
