version: '3.4'

services:
  kattbot:
    build:
      context: .
      dockerfile: Kattbot/Dockerfile
    depends_on:
      - kattbot-pgsql

  kattbot-pgsql:
    image: postgres:15.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: kattbot
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: kattbot-dev
    volumes:
      - kattbot-pgdata:/var/lib/postgresql/data

volumes:
  kattbot-pgdata:
    
