using System.Text.Json.Serialization;

namespace Kattbot.Common.Models.KattGpt;

public record ChatCompletionChoice
{
    /// <summary>
    ///     The index of the choice in the list of choices.
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    ///     A chat completion message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public ChatCompletionMessage Message { get; set; } = null!;

    /// <summary>
    ///     The reason the model stopped generating tokens.
    ///     This will be 'stop' if the model hit a natural stop point or a provided stop sequence,
    ///     'length' if the maximum number of tokens specified in the request was reached,
    ///     'content_filter' if content was omitted due to a flag from our content filters
    ///     or 'tool_calls' if the model called a tool.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public ChoiceFinishReason FinishReason { get; set; }
}
