using System.Text.Json.Serialization;

namespace Kattbot.Common.Models.KattGpt;

public record ChatCompletionFunctionCall
{
    public ChatCompletionFunctionCall(string name, string arguments)
    {
        Name = name;
        Arguments = arguments;
    }

    /// <summary>
    ///     The name of the function to call.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; }

    /// <summary>
    ///     The arguments to call the function with, as generated by the model in JSON format.
    ///     Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your
    ///     function schema.
    ///     Validate the arguments in your code before calling your function.
    /// </summary>
    [JsonPropertyName("arguments")]
    public string Arguments { get; }
}
