name: Restart

on:
  workflow_dispatch
  
jobs:
  restart:
    runs-on: ubuntu-latest
    steps: 
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:  
        host: ${{secrets.VPS_HOST}}
        port: ${{secrets.VPS_PORT}}
        username: ${{secrets.KATTBOT_USER}}
        key: ${{secrets.KATTBOT_KEY}}
        passphrase: ${{secrets.KATTBOT_PASSPHRASE}}   
        script: systemctl --user restart kattbot
