using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Kattbot.Services.GptImages;

#pragma warning disable SA1402 // File may only contain a single type
public record CreateImageRequest
{
    /// <summary>
    ///     Gets or sets a text description of the desired image(s). The maximum length is 1000 characters.
    ///     https://platform.openai.com/docs/api-reference/images/create#images/create-prompt.
    /// </summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = null!;

    /// <summary>
    ///     Gets or sets the model to use for image generation.
    ///     Defaults to dall-e-2
    ///     https://platform.openai.com/docs/api-reference/images/create#images-create-model.
    /// </summary>
    [JsonPropertyName("model")]
    public string? Model { get; set; }

    /// <summary>
    ///     Control the content-moderation level for images generated by gpt-image-1.
    ///     Must be either "low" for less restrictive filtering or "auto".
    ///     Defaults to "auto".
    ///     https://platform.openai.com/docs/api-reference/images/create#images-create-moderation
    /// </summary>
    [JsonPropertyName("moderation")]
    public string? Moderation { get; set; }

    /// <summary>
    ///     Gets or sets the number of images to generate. Must be between 1 and 10.
    ///     Defaults to 1.
    ///     https://platform.openai.com/docs/api-reference/images/create#images/create-n.
    /// </summary>
    [JsonPropertyName("n")]
    public int? N { get; set; }

    /// <summary>
    ///     The compression level (0-100%) for the generated images.
    ///     This parameter is only supported for gpt-image-1 with the webp or jpeg output formats
    ///     Defaults to 100.
    ///     https://platform.openai.com/docs/api-reference/images/create#images-create-output_compression
    [JsonPropertyName("output_compression")]
    public string? OutputCompression { get; set; }

    /// <summary>
    ///     The format in which the generated images are returned.
    ///     This parameter is only supported for gpt-image-1.
    ///     Must be one of png, jpeg, or webp.
    ///     Defaults to png.
    ///     https://platform.openai.com/docs/api-reference/images/create#images-create-output_format
    /// </summary>
    [JsonPropertyName("output_format")]
    public string? OutputFormat { get; set; }

    /// <summary>
    ///     The quality of the image that will be generated.
    ///     - auto will automatically select the best quality for the given model.
    ///     - high, medium and low are supported for gpt-image-1.
    ///     Defaults to "auto".
    ///     https://platform.openai.com/docs/api-reference/images/create#images-create-quality.
    /// </summary>
    [JsonPropertyName("quality")]
    public string? Quality { get; set; }

    /// <summary>
    ///     The size of the generated images.
    ///     Must be one of 1024x1024, 1536x1024 (landscape), 1024x1536 (portrait), or auto.
    ///     Defaults to auto.
    ///     https://platform.openai.com/docs/api-reference/images/create#images/create-size.
    /// </summary>
    [JsonPropertyName("size")]
    public string? Size { get; set; }

    /// <summary>
    ///     Gets or sets a unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    ///     https://platform.openai.com/docs/api-reference/chat/create#chat/create-user.
    /// </summary>
    [JsonPropertyName("user")]
    public string? User { get; set; }
}

public record CreateImageResponse
{
    [JsonPropertyName("created")]
    public long Created { get; set; }

    [JsonPropertyName("data")]
    public IEnumerable<ImageResponseData> Data { get; set; } = null!;
}

public record ImageResponseData
{
    [JsonPropertyName("b64_json")]
    public string B64Json { get; set; } = null!;
}

public record ImageResponseErrorWrapper
{
    [JsonPropertyName("error")]
    public ImageResponseError Error { get; set; } = null!;
}

public record ImageResponseError
{
    [JsonPropertyName("code")]
    public string Code { get; set; } = null!;

    [JsonPropertyName("message")]
    public string Message { get; set; } = null!;

    [JsonPropertyName("param")]
    public string Param { get; set; } = null!;

    [JsonPropertyName("type")]
    public string Type { get; set; } = null!;
}
